### PR TITLE
.gitignore: add /npm-debug.log

### PR DESCRIPTION
**Pull request by diogocp**

### CODE REVIEW

**Comment by andrewrk** [comment]
I prefer not having npm-debug.log in my .gitignore so that git tells me when npm-debug.log exists, so that I can delete it from my hard drive. Ideally npm-debug.log will never exist.

**Comment by andrewrk** [comment]
if this helps gentoo packaging somehow let me know, I'll make an exception for that.

**Comment by diogocp** [comment]
No, I just wanted git to shut up about it. I'm not really familiar with how npm works.

**Comment by andrewrk** [comment]
yeah, it's really annoying, sorry about that.

**Comment by diogocp** [comment]
Unfortunately I don't think node/npm is very well supported in Gentoo at the moment (anything that uses its own package manager is tricky), so it may be a while until we can get groovebasin in.

**Comment by andrewrk** [comment]
I ran into that problem with Debian as well. NixOS on the other hand was a breeze. I ran one command and it basically built the package for me by reading package.json.

**Comment by andrewrk** [comment]
https://github.com/NixOS/nixpkgs/pull/8353

`pkgs/applications/audio/groovebasin/package.nix` was auto generated.

pretty cool eh?

**Comment by diogocp** [comment]
I've looked a bit into NixOS and it looks amazing. I'll have to try it sometime.

**Pull request closed without merging**
