### PR TITLE
allocator fixes, std.log impl, and a crash on empty library fix

### PR DESCRIPTION
**Pull request by mattnite**
- I realized that blindly fixing allocgate caused crashes wrt the js/wasm interface, we were passing an allocator pointer back and forth, but structs are different -- I've read up on this topic but I need to do more reading before I can figure out how to do things properly, so I've gone back to passing an allocator pointer.
- Added std.log impl and switched to using scoped logs for websocket and ui components.
- Fix a crash I found from there being no tracks in the library, which resulted in zig pointer being null

### CODE REVIEW

**Comment by andrewrk** [comment]
Thanks! I'll need to do a lot more work on the ffmpeg package before it will support all these other ISAs. Maybe we disable the checks we know will fail every time until I get them working?

I don't really plan to go all in on the ffmpeg package until the official zig package manager arrives.

**Comment by andrewrk** [comment]
This is the main issue: 

https://github.com/andrewrk/groovebasin/blob/fd0baecb7f21c4425b708090a99006700c6e4200/deps/ffmpeg/config.h#L1

Right now this config file is hard coded for x86_64-linux-musl.

**Comment by thejoshwolfe** [comment]
> * Added std.log impl and switched to using scoped logs for websocket and ui components.

Thanks! I actually tried that once and ran into a compiler bug. Never got around to attempting it again.

**Comment by mattnite** [comment]
Thanks for the patches! I was away from my computer this weekend and helpless to do anything about it

**Pull request merged**
